version: '2.4'
services:
  bert_mult:
    restart: always
    #image: deeppavlov/base-cpu
    image: pavlovtrain
    environment:
       - CONFIG=ner_ontonotes_bert_mult
    volumes:
      - ./bert_mult/deeppavlov/my_dp_components:/root/.deeppavlov
      - ./bert_mult/saved_models/:/saved_models
      - ./bert_mult/current_model/:/current_model
      - ./bert_mult/deeppavlov/my_dp_envs:/venv
      - ./bert_mult/web:/web
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5550:5000"

  pavlov_rest_1:
    restart: always
    image: pavlovrest
    environment:
       - CONFIG=ner_ontonotes_bert_mult
       - PORT=5000
    volumes:
      - ./bert_mult/current_model:/root/.deeppavlov
      - ./pavlov_rest/deeppavlov/my_dp_envs:/venv
    ports:
      - "5556:5000"

  pavlov_rest_2:
    restart: always
    image: pavlovrest
    environment:
       - CONFIG=ner_ontonotes_bert_mult
       - PORT=5001
    volumes:
      - ./bert_mult/current_model/:/root/.deeppavlov
      - ./pavlov_rest/deeppavlov/my_dp_envs:/venv
    ports:
      - "5557:5001"

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data  
    ports:
      - "5432:5432"

  pgadmin:
    restart: always
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
    ports:
      - "8765:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"


volumes:
  db-data:
  pgadmin-data:
